# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a5d55ffdb42632450137219a9b90345e85efabf7ac961fd533df153b583db8eef7af172380afb93fce4243933c47d0cade27299b1cc9deaeaa2f808a19f9ef2

test:
  secret_key_base: a9a3e51b64a9c20320dd5767e8f329dcfb7a44eaeb75f3e97f0e6264a364ba211d8e9b07ab6ab04bfe3d1f60fe3e9e645dbf2f8813c7a0ae193a6d6cd5d3addc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
